config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get    "tasks",          to: "tasks#index"
  get    "tasks/new",      to: "tasks#new",     as: "new_task"
  post   "tasks",          to: "tasks#create"
  get    "tasks/:id",      to: "tasks#show",    as: "task"
  get    "tasks/:id/edit", to: "tasks#edit",    as: "edit"
  patch  "tasks/:id",      to: "tasks#update"
  delete "tasks/:id",      to: "tasks#destroy", as: "destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    # redirect_to task_path(@task)
  end

  def task_params
    params.required(:task).permit(:title, :details)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1 class="title"><i class="far fa-edit"></i>Edit Task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.check_box :completed %>

  <%=f.submit  %>
<% end %>

<i class="fas fa-undo-alt"></i><%= link_to "Back to tasks list", tasks_path %>

app/views/tasks/index.html.erb
<h1 class="title"><i class="fas fa-list-ul"></i>My Tasks</h1>

<h3>To do:</h3>

<ul><% @tasks.each do |task| %>
  <li><%= link_to task.title, task_path(task) %></li>
  <i class="fas fa-trash-alt"><%= link_to "Delete", destroy_path(task) %></i>
  <% end %>
</ul>

<i class="far fa-plus-square"></i><%= link_to "Add a new task", new_task_path %>

app/views/tasks/new.html.erb
<h1 class="title">New Task</h1>

<%= form_for(@task) do |f| %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= f.label :title %>
  <%=f.text_field :title  %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
  <% end %>

<!-- <form action="/new" method="post">
  <label for="title">Title:</label>
  <input type="text" name="task[title]" id="title" >

  <label for="details">Details:</label>
  <input type="text" name="task[details]" id="details" >

  <input type="submit" class="btn" value="Create Task">
</form>
 -->
<%= link_to "Back to tasks list", tasks_path %>

app/views/tasks/show.html.erb
<h1 class="title"><i class="far fa-play-circle"></i><%= @task.title %></h1>

 <h3><i class="fas fa-info-circle"></i><%= @task.details %></h3>

<p><i class="far fa-edit"></i><%= link_to "Edit task", edit_path %></p>

<p><i class="fas fa-undo-alt"></i><%= link_to "Back to tasks list", tasks_path %></p>